---

redhat_image_builder_packages:
  - bash-completion
  - cockpit
  - cockpit-image-builder
  - composer-cli
  - firewalld
  - httpd
  - lorax
  - osbuild-composer
  - pykickstart
  - python3
  - rsync
  - syslinux
  - weldr-client
