---

- name: Red Hat Ansible Automation Platform (AAP) Installation
  ansible.builtin.import_tasks: install.yml
  tags: aap_install

- name: Red Hat Ansible Automation Platform (AAP) Configuration
  ansible.builtin.import_tasks: configure.yml
  tags: aap_configure
