---

- name: scap | Load SCAP profile specific variables
  ansible.builtin.include_vars: "{{ __redhat_ansible_automation_platform_scap_vars_file }}"
  vars:
    __redhat_ansible_automation_platform_scap_vars_file: "{{ role_path }}/vars/scap/{{ redhat_ansible_automation_platform_scap_profile | regex_replace('xccdf_org.*.content_profile_', '') }}"
  when:
    - redhat_ansible_automation_platform_scap_profile is defined
    - __redhat_ansible_automation_platform_scap_vars_file is file

- name: scap | Security Content Automation Protocol (SCAP) Remediation
  ansible.builtin.include_role:
    name: infra.soe.redhat_scap
    apply:
      tags: aap_scap
  vars:
    redhat_scap_tailoring_title: "{{ redhat_ansible_automation_platform_scap_tailoring_title }}"
    redhat_scap_tailoring_description: "{{ redhat_ansible_automation_platform_scap_tailoring_description }}"
    redhat_scap_tailoring_exceptions: "{{ redhat_ansible_automation_platform_scap_tailoring_exceptions }}"
  tags: aap_scap
  when: redhat_ansible_automation_platform_scap_profile is defined
