---

- name: users | AAP IdM Users
  ansible.builtin.import_role:
    name: redhat_idm_users
  vars:
    ipaadmin_password: "{{ idm_admin_password | default(omit) }}"
  run_once: true
  when:
    - redhat_idm_users is defined and redhat_idm_users | length > 0
    - idm_admin_password is defined
  tags:
    - redhat_idm_users
    - idm_configure

- name: users | AAP IdM Groups
  ansible.builtin.import_role:
    name: redhat_idm_groups
  vars:
    ipaadmin_password: "{{ idm_admin_password | default(omit) }}"
  run_once: true
  when:
    - redhat_idm_groups is defined and redhat_idm_groups | length > 0
    - idm_admin_password is defined
  tags:
    - redhat_idm_groups
    - idm_configure

- name: users | AAP IdM Host-based Access Control
  ansible.builtin.import_role:
    name: redhat_idm_hbac
  vars:
    ipaadmin_password: "{{ idm_admin_password | default(omit) }}"
  run_once: true
  when:
    - redhat_idm_hbac is defined and redhat_idm_hbac | length > 0
    - idm_admin_password is defined
  tags:
    - redhat_idm_hbac
    - idm_configure

- name: users | Enable systemd lingering for AAP service user
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ aap_service_user }}"
    creates: "/var/lib/systemd/linger/{{ aap_service_user }}"
  when: aap_service_user != 'root'
