---

- name: certificate | Configure Red Hat Cockpit IdM Service
  ansible.builtin.include_role:
    name: redhat_idm_service
  vars:
    redhat_idm_service_principal: "{{ redhat_cockpit_idm_service_principal }}"
    redhat_idm_service_tls_enabled: true
    redhat_idm_service_tls_request_id: "redhat_cockpit_idm_service"
    redhat_idm_service_tls_sans: "{{ redhat_cockpit_idm_service_tls_sans | default([]) }}"
  tags: redhat_idm_service
