---

- name: certificate | Checksum Satellite Server IdM service certificate
  ansible.builtin.stat:
    path: "/etc/pki/{{ redhat_satellite_idm_service_request_id }}/service.crt"
    checksum_algorithm: sha256
    get_checksum: true
  register: _redhat_satellite_idm_service_certificate

- name: certificate | Checksum Satellite Server certificate
  ansible.builtin.stat:
    path: "/root/ssl-build/{{ satellite_hostname }}/{{ satellite_hostname }}-apache.crt"
    checksum_algorithm: sha256
    get_checksum: true
  register: _redhat_satellite_server_certificate

- name: certificate | Run satellite-installer to configure SSL certificates
  ansible.builtin.command:
    cmd: >-
      satellite-installer
      --certs-server-cert /etc/pki/{{ redhat_satellite_idm_service_request_id }}/service.crt
      --certs-server-key /etc/pki/{{ redhat_satellite_idm_service_request_id }}/private/service.key
      --certs-server-ca-cert /etc/pki/{{ redhat_satellite_idm_service_request_id }}/ipa-ca.crt
      --certs-update-server
      --certs-update-server-ca
  register: __redhat_satellite_installer_result
  changed_when: >-
    'Success!' in __redhat_satellite_installer_result.stdout
  notify: Verify Satellite Server certificate
  when: >-
    not _redhat_satellite_server_certificate.stat.exists or
    _redhat_satellite_idm_service_certificate.stat.checksum != _redhat_satellite_server_certificate.stat.checksum

- name: certificate | Flush handlers
  ansible.builtin.meta: flush_handlers
