---

- name: certificate | Configure Red Hat Keycloak IdM Service
  ansible.builtin.include_role:
    name: redhat_idm_service
  vars:
    redhat_idm_service_principal: "{{ keycloak_idm_service_principal }}"
    redhat_idm_service_user: "{{ keycloak_idm_service_user }}"
    redhat_idm_service_group: "{{ keycloak_idm_service_group }}"
    redhat_idm_service_tls_enabled: true
    redhat_idm_service_tls_request_id: "keycloak_idm_service"
    redhat_idm_service_tls_sans: "{{ keycloak_idm_service_tls_sans | default([]) }}"
  tags: redhat_idm_service
