---

- name: Red Hat Build of Keycloak (RHBK) Installation
  ansible.builtin.import_tasks: install.yml
  tags: keycloak_install

- name: Red Hat Build of Keycloak (RHBK) Configuration
  ansible.builtin.import_tasks: configure.yml
  tags: keycloak_configure

- name: Red Hat Build of Keycloak (RHBK) SCAP Remediation
  ansible.builtin.import_tasks: scap.yml
  tags: keycloak_scap
