---

dependencies:
  - name: Application Server Firewall
    role: infra.soe.firewall
    vars:
      firewall_enabled: "{{ application_server_firewall_enabled }}"
      firewall: "{{ application_server_firewall }}"
    tags:
      - app_server_firewall
      - firewall
    when: application_server_firewall_enabled
