---

dependencies:
  - name: Red Hat Identity Management (IdM) Firewall
    role: infra.soe.firewall
    vars:
      firewall_enabled: "{{ redhat_identity_management_firewall_enabled }}"
      firewall: "{{ redhat_identity_management_firewall }}"
      firewall_log_denied: "{{ redhat_identity_management_firewall_log_denied }}"
      firewall_disable_conflicting_services: "{{ redhat_identity_management_firewall_disable_conflicting_services }}"
    tags:
      - idm_firewall
      - firewall
    when: redhat_identity_management_firewall_enabled
