---

- name: Set platform/version specific variables
  ansible.builtin.import_tasks: set_vars.yml
  tags:
    - image_builder_install
    - image_builder_configure

- name: Red Hat Image Builder Installation
  ansible.builtin.import_tasks: install.yml
  tags: image_builder_install

- name: Red Hat Image Builder Configuration
  ansible.builtin.import_tasks: configure.yml
  tags: image_builder_configure

- name: Red Hat Image Builder SCAP Remediation
  ansible.builtin.import_tasks: scap.yml
  tags: image_builder_scap
