---

- name: install | Check if system is ostree
  ansible.builtin.stat:
    path: /run/ostree-booted
  register: __application_server_ostree_booted_stat

- name: install | Install Podman (Standard RHEL/Fedora)
  ansible.builtin.dnf:
    name: podman
    state: present
  when: not __application_server_ostree_booted_stat.stat.exists
  tags: podman

- name: install | Install Podman (OSTree)
  community.general.rpm_ostree_pkg:
    name:
      - podman
      - python3-rpm  # required for redhat.rhel_system_roles.podman package_facts
      # https://docs.ansible.com/projects/ansible-core/2.16/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user
      - acl          # required for ansible unprivileged user management
    state: present
  register: __application_server_ostree_package_install
  when: __application_server_ostree_booted_stat.stat.exists

- name: install | Reboot host following ostree package install
  ansible.builtin.reboot:
  when:
    - __application_server_ostree_booted_stat.stat.exists
    - __application_server_ostree_package_install.changed
