---

- name: Create Red Hat Identity Management groups
  redhat.rhel_idm.ipagroup:
    ipaadmin_password: "{{ redhat_idm_groups_admin_password }}"
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    description: "{{ item.description }}"
    user: "{{ item.users | default(omit) }}"
    group: "{{ item.groups | default(omit) }}"
    state: present
  loop: "{{ redhat_idm_groups | default([]) }}"
  no_log: "{{ no_log_enabled | default(true) }}"
