---

- name: Application Server
  hosts: "{{ target_hosts | default('application_server') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - fedora
    - app_server
  roles:
    - infra.soe.application_server
