---

- name: Local Users
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - fedora
    - microsoft
    - local_users
  roles:
    - infra.soe.local_users
