---

- name: Configure Local Storage
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  become: true
  tags:
    - local_storage
  pre_tasks:
    - name: Ensure LVM Physical Volume is using all available space
      ansible.builtin.command: /bin/growpart {{ local_storage_pv.device }} {{ local_storage_pv.partition }}
      register: growpart_result
      changed_when: "'CHANGED' in growpart_result.stdout"
      failed_when: >
        growpart_result.rc != 0 and
        'NOCHANGE' not in growpart_result.stdout
      when: local_storage_pv is defined
  roles:
    - role: redhat.rhel_system_roles.storage
      storage_pools: "{{ local_storage_lv }}"
      tags: redhat.rhel_system_roles.storage
      when: local_storage_lv is defined
