---

- name: Local Storage
  hosts: "{{ target_hosts | default('redhat:fedora') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - fedora
    - local_storage
  roles:
    - infra.soe.local_storage
