---

- name: NetBird WireGuard Mesh Virtual Private Network (VPN) Control Plane
  hosts: "{{ target_hosts | default('netbird') }}"
  gather_facts: false
  become: true
  tags:
    - netbird
  roles:
    - infra.soe.netbird
