---

- name: Verify Ansible Connectivity
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: false
  tags:
    - redhat
    - fedora
    - microsoft
    - ping
  roles:
    - infra.soe.ping
