---

- name: Reboot
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  become: true
  tags:
    - reboot
  tasks:
    - name: Reboot
      ansible.builtin.include_role:
        name: infra.soe.reboot
      when:
        - reboot | default(false) | bool
