---

- name: Red Hat Cockpit
  hosts: "{{ target_hosts | default('redhat:!identity_management:!satellite') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - cockpit
  roles:
    - infra.soe.redhat_cockpit
