---
# https://console.redhat.com/ansible/automation-hub/collections/published/redhat/rhbk/documentation/role/rhbk

- name: Red Hat Build of Keycloak (RHBK)
  hosts: "{{ target_hosts | default('keycloak') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - keycloak
  roles:
    - infra.soe.redhat_keycloak
