---

- name: Red Hat Image Builder
  hosts: "{{ target_hosts | default('image_builder') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - image_builder
  roles:
    - role: infra.soe.redhat_image_builder
