---

- name: Red Hat Enterprise Linux (RHEL) registration via Red Hat Subscription Management (RHSM)
  hosts: "{{ target_hosts | default('redhat') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - register
  roles:
    - infra.soe.redhat_register
