---

- name: Configure Red Hat Identity Management (IdM) service integration
  hosts: "{{ target_hosts | default('redhat') }}"
  gather_facts: false
  tags:
    - idm_service
  roles:
    - infra.soe.redhat_idm_service
