---

- name: Red Hat Identity Management (IdM)
  hosts: "{{ target_hosts | default('idm_server:idm_replica') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - idm
  roles:
    - infra.soe.redhat_identity_management
