---

- name: Red Hat Satellite Server
  hosts: "{{ target_hosts | default('satellite_server') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - satellite
  pre_tasks:
    - name: Install Red Hat Satellite Server
      tags: satellite_install
      block:
        - name: Ensure host network is prepared for Satellite Server Installer
          ansible.builtin.import_role:
            name: infra.soe.redhat_satellite
            tasks_from: network

        - name: Flush handlers
          ansible.builtin.meta: flush_handlers

        - name: Run Satellite Server Installer
          ansible.builtin.import_role:
            name: infra.soe.redhat_satellite
            tasks_from: install

        - name: Configure Satellite Server Certificate
          ansible.builtin.include_role:
            name: infra.soe.redhat_satellite
            tasks_from: certificate
            apply:
              tags: redhat_idm_service
          tags: redhat_idm_service
          when: satellite_idm_service_principal is defined
          vars:
            ipaadmin_password: "{{ idm_admin_password }}"

        - name: Flush handlers
          ansible.builtin.meta: flush_handlers
  tasks:
    - name: Configure Red Hat Satellite Server
      tags: satellite_configure
      block:
        # FIXME Finish Satellite Keycloak
        - name: Configure Satellite Server Keycloak Single-Sign-On (SSO)
          ansible.builtin.include_role:
            name: infra.soe.redhat_satellite
            tasks_from: keycloak
            apply:
              tags: satellite_keycloak
          tags: satellite_keycloak
          when: satellite_idm_service_principal | default(false)

        - name: Configure Satellite Server Components
          ansible.builtin.import_role:
            name: infra.soe.redhat_satellite
            tasks_from: configure
          when: satellite_idm_service_principal | default(false)
