---

- name: Red Hat Satellite Server
  hosts: "{{ target_hosts | default('satellite_server') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - satellite
  roles:
    - infra.soe.redhat_satellite
