---

- name: Red Hat Identity Management (IdM) Client Registration
  hosts: "{{ target_hosts | default('redhat:!identity_management') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - idm_register
  roles:
    - infra.soe.redhat_idm_register
