---

- name: Update Red Hat Enterprise Linux (RHEL)
  hosts: "{{ target_hosts | default('redhat:!satellite') }}"
  gather_facts: false
  become: true
  tags:
    - redhat
    - update
  roles:
    - infra.soe.redhat_update
