---

- name: Configure Local Users
  ansible.builtin.import_playbook: local_users.yml

- name: Register Red Hat Enterprise Linux (RHEL) Hosts
  ansible.builtin.import_playbook: redhat_register.yml

- name: Configure Local Storaged
  ansible.builtin.import_playbook: local_storage.yml

- name: Red Hat Enterprise Linux (RHEL) Update
  ansible.builtin.import_playbook: redhat_update.yml

- name: Red Hat Identity Management (IdM)
  ansible.builtin.import_playbook: redhat_identity_management.yml

- name: Red Hat Enterprise Linux (RHEL) Identity Management (IdM) Registration
  ansible.builtin.import_playbook: redhat_idm_register.yml

- name: Red Hat Enterprise Linux (RHEL) Cockpit Web Console
  ansible.builtin.import_playbook: redhat_cockpit.yml

- name: Red Hat Satellite Server
  ansible.builtin.import_playbook: redhat_satellite.yml

- name: Red Hat Build of Keycloak (RHBK)
  ansible.builtin.import_playbook: redhat_keycloak.yml

- name: Caddy Transport Layer Security (TLS) Reverse Proxy
  ansible.builtin.import_playbook: caddy.yml

- name: NetBird WireGuard Mesh Virtual Private Network (VPN)
  ansible.builtin.import_playbook: netbird.yml

- name: Red Hat Ansible Automation Platform (AAP)
  ansible.builtin.import_playbook: redhat_ansible_automation_platform.yml

- name: Red Hat Image Builder
  ansible.builtin.import_playbook: redhat_image_builder.yml

- name: Application Server
  ansible.builtin.import_playbook: application_server.yml

- name: Firewall
  ansible.builtin.import_playbook: firewall.yml

- name: Security Content Automation Protocol (SCAP) Remediation
  ansible.builtin.import_playbook: redhat_scap.yml

- name: Reboot
  ansible.builtin.import_playbook: reboot.yml
