---

- name: Register Red Hat Enterprise Linux (RHEL) Hosts
  ansible.builtin.import_playbook: redhat_register.yml

- name: Update Red Hat Enterprise Linux (RHEL) Hosts
  ansible.builtin.import_playbook: redhat_update.yml

- name: Host Firewall
  ansible.builtin.import_playbook: firewall.yml

- name: Red Hat Enterprise Linux (RHEL) Cockpit Web Console
  ansible.builtin.import_playbook: redhat_cockpit.yml

- name: Red Hat Identity Management (IdM)
  ansible.builtin.import_playbook: redhat_identity_management.yml

- name: Red Hat Satellite Server
  ansible.builtin.import_playbook: redhat_satellite.yml
